mysql:
    username: username
    password: password
    address: 192.168.210.143
    dbname: rec_system
    charset: utf8

elasticsearch:
    address: [
        192.168.210.149,
        192.168.210.150
    ]
    port: 9200
