DROP TRIGGER IF EXISTS TRIGGER_LOOKUP_CAT;

delimiter //

CREATE TRIGGER TRIGGER_LOOKUP_CAT
BEFORE INSERT ON EP_INFO
FOR EACH ROW
BEGIN

	DECLARE VAR INT;
	SET @VAR = NULL;

    SELECT CAT_ID INTO @var FROM ITEM_CAT
    WHERE CAT1 <=> NEW.CAT1
    AND CAT2 <=> NEW.CAT2
    AND CAT3 <=> NEW.CAT3
    AND CAT4 <=> NEW.CAT4;

    SET NEW.CAT_ID = @VAR;

END//

delimiter ;

SHOW TRIGGERS;

-- TEST CASES

INSERT EP_INFO VALUES (-1, '1', 'item1', NULL, 'cat1', 'cat2', 'cat3', 'cat4');

SELECT * FROM EP_INFO WHERE SHOPPING_ID = -1;
DELETE FROM REC_SYSTEM.EP_INFO WHERE SHOPPING_ID = -1;
