CREATE OR REPLACE VIEW CAT_MAP_QUEUE AS
SELECT
SHOPPING_ID,
ITEM_CODE,
ITEM_NAME,
CAT_ID,
CAT1,
CAT2,
CAT3,
CAT4
FROM EP_INFO
WHERE CAT_ID IS NULL;

CREATE OR REPLACE VIEW CAT_MAP_VIEW AS
SELECT
c.CAT_ID AS CAT_ID,
c.INTG_ID AS INTG_ID,
c.UPDATE_TIME AS UPDATE_TIME,
a.CAT1 AS CAT1,
a.CAT2 AS CAT2,
a.CAT3 AS CAT3,
a.CAT4 AS CAT4,
b.INTG_CAT1 AS INTG_CAT1,
b.INTG_CAT2 AS INTG_CAT2,
b.INTG_CAT3 AS INTG_CAT3,
b.INTG_CAT4 AS INTG_CAT4
FROM ITEM_CAT a, INTG_CAT b, CAT_MAP c
WHERE a.CAT_ID = c.CAT_ID
AND b.INTG_ID = c.INTG_ID
ORDER BY c.CAT_ID;

CREATE OR REPLACE VIEW EP_INFO_VIEW AS
SELECT
a.SHOPPING_ID AS SHOPPING_ID,
b.INTG_ID AS INTG_ID,
a.ITEM_CODE AS ITEM_CODE,
a.ITEM_NAME AS ITEM_NAME,
a.CAT1 AS CAT1,
a.CAT2 AS CAT2,
a.CAT3 AS CAT3,
a.CAT4 AS CAT4,
b.INTG_CAT1 AS INTG_CAT1,
b.INTG_CAT2 AS INTG_CAT2,
b.INTG_CAT3 AS INTG_CAT3,
b.INTG_CAT4 AS INTG_CAT4
FROM EP_INFO a, INTG_CAT b,CAT_MAP c
WHERE a.CAT_ID = c.CAT_ID
AND c.INTG_ID = b.INTG_ID;